name: Deploy to GitHub pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build website for GitHub pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fetch tags
        run: git fetch --tags origin
      - name: Copy latest to website
        run: |
          mkdir website
          cp crosspuzzle.js crosspuzzle.css favicon.ico website/
          cp examples.html website/index.html
      - name: Copy releases to website
        run: |
          examples=`cat examples.html`
          start=${examples%$"<div class='main'>"*}
          echo "$start" > website/releases.html
          printf "<div class='main'>\n<h1>Releases</h1>\n" >> website/releases.html
          releases=""
          for tag in $(git tag -l v*.*.*)
          do
            mkdir website/$tag
            git checkout $tag
            cp *.js *.css website/$tag
            r="<h2>$tag</h2>\n"
            r="$r<p><a href='https://github.com/mscroggs/crosspuzzle/releases/tag/$tag'>$tag on GitHub</a></p>\n"
            r="$r<p>To include crosspuzzle $tag on your web page, include the following in your <code>&lt;head&gt;</code>:</p>\n"
            r="$r<div style='margin:0px 40px'><code>\n"
            next=""
            for js_file in $(ls *.js)
            do
              r="$r$next&lt;script type='text/javascript' src='https://mscroggs.github.io/crosspuzzle/$tag/$js_file'&gt;&lt;/script&gt;"
              next="<br />\n"
            done
            for css_file in $(ls *.css)
            do
              r="$r$next&lt;link type='text/css' rel='stylesheet' src='https://mscroggs.github.io/crosspuzzle/$tag/$css_file' /&gt;"
              next="<br />\n"
            done
            r="$r\n</code></div>\n"
            releases="$r$releases"
          done
          printf "$releases" >> website/releases.html
          printf "</div>\n</body>\n</html>\n" >> website/releases.html
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'website'

  deploy:
    name: Deploy to GitHub pages
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

